{% set version = "1.10.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pillar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pillar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pillar/pillar_{{ version }}.tar.gz
  sha256: 2cdbe3fe1b28b62530880ab26fc3c874e0dd5060767ae1a8ee5685f65e56d645

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-crayon >=1.3.4
    - r-ellipsis
    - r-fansi
    - r-lifecycle
    - r-rlang >=0.3.0
    - r-utf8 >=1.1.0
    - r-vctrs >=0.2.0
  run:
    - r-base
    - r-cli
    - r-crayon >=1.3.4
    - r-ellipsis
    - r-fansi
    - r-lifecycle
    - r-rlang >=0.3.0
    - r-utf8 >=1.1.0
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('pillar')"           # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

about:
  home: https://github.com/r-lib/pillar
  license: GPL-3.0-only
  summary: Provides 'pillar' and 'colonnade' generics designed for formatting columns of data using the full range of colours provided by modern terminals.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: pillar
# Title: Coloured Formatting for Columns
# Version: 1.4.2
# Authors@R: c( person("Kirill", "Muller", , "krlmlr+r@mailbox.org", role = c("aut", "cre")), person("Hadley", "Wickham", role = "aut"), person("RStudio", role = "cph") )
# Description: Provides 'pillar' and 'colonnade' generics designed for formatting columns of data using the full range of colours provided by modern terminals.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/r-lib/pillar
# BugReports: https://github.com/r-lib/pillar/issues
# Imports: cli, crayon (>= 1.3.4), fansi, rlang (>= 0.3.0), utf8 (>= 1.1.0), vctrs
# Suggests: knitr, lubridate, testthat, withr
# RoxygenNote: 6.1.1
# Collate: 'capital.R' 'compat-lifecycle.R' 'compat-purrr.R' 'dim.R' 'empty-data.R' 'extent.R' 'lengths.R' 'multi.R' 'ornament.R' 'pillar-package.R' 'pillar.R' 'rowid-capital.R' 'rowid-data.R' 'rowid-title.R' 'rowid-type.R' 'scientific.R' 'shaft.R' 'shaft-simple.R' 'sigfig.R' 'spark-bar.R' 'spark-line.R' 'strrep.R' 'styles.R' 'testthat.R' 'tick.R' 'title.R' 'type-sum.R' 'type.R' 'utils.R' 'vctrs.R' 'width.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2019-06-29 16:08:04 UTC; kirill
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2019-06-29 16:40:03 UTC
